import { defineConfig, Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { viteSingleFile } from 'vite-plugin-singlefile';
import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';

const CONFIG_PLACEHOLDER = '{{SCHEDULER_CONFIG}}';

function embedDashboard(): Plugin {
  return {
    name: 'embed-dashboard',
    apply: 'build',
    async writeBundle(_options, bundle) {
      const htmlFile = Object.keys(bundle).find(name => name.endsWith('.html'));
      if (!htmlFile) {
        console.warn('[scheduler-dash-ui] No HTML file found in bundle');
        return;
      }
      // Keep the placeholder as-is so the server can inject the correct absolute URL
      const html = (bundle[htmlFile] as { source: string }).source;
      const content =
        `// Auto-generated by build process\n` +
        `export const dashboardHtml: string = ${JSON.stringify(html)};\n` +
        `export const CONFIG_PLACEHOLDER = ${JSON.stringify(CONFIG_PLACEHOLDER)};\n`;
      const outPath = resolve(__dirname, '../scheduler-dash/src/ui/dashboard.ts');
      mkdirSync(dirname(outPath), { recursive: true });
      writeFileSync(outPath, content);
      console.log('[scheduler-dash-ui] Embedded dashboard HTML');
    },
  };
}

export default defineConfig({
  plugins: [react(), viteSingleFile(), embedDashboard()],
  resolve: {
    alias: { '@': resolve(__dirname, 'src') },
  },
  build: {
    outDir: 'dist',
    target: 'esnext',
    minify: 'esbuild',
    assetsInlineLimit: 100_000_000,
    chunkSizeWarningLimit: 100_000_000,
  },
});
