import { defineConfig, Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { viteSingleFile } from 'vite-plugin-singlefile';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';

function embedDashboard(): Plugin {
  return {
    name: 'embed-dashboard',
    closeBundle() {
      const html = readFileSync('./dist/index.html', 'utf-8');
      const content =
        `// Auto-generated by apps/dashboard build — do not edit manually.\n` +
        `export const dashboardHtml = ${JSON.stringify(html)};\n`;
      const outPath = resolve(__dirname, '../../packages/scheduler-dash/src/ui/dashboard.ts');
      mkdirSync(dirname(outPath), { recursive: true });
      writeFileSync(outPath, content);
      console.log('[embed-dashboard] wrote dashboard.ts to scheduler-dash package');
    },
  };
}

export default defineConfig({
  plugins: [react(), viteSingleFile(), embedDashboard()],
  resolve: {
    alias: { '@': resolve(__dirname, 'src') },
  },
  build: {
    outDir: 'dist',
    target: 'esnext',
    assetsInlineLimit: 100_000_000,
    chunkSizeWarningLimit: 100_000_000,
  },
});
